[package]
name = "libxid"
version = "0.1.0"
authors = ["Jérôme Renard <jeromer@fastmail.net>"]
edition = "2018"

[dependencies]
rand = "0.6"
gethostname = "0.2.0"
md5 = "0.6.1"
crc32fast = "1.1.2"
byteorder = "1.3.1"
data-encoding = "2.1.2"
